---
- hosts: all
  tasks:
  - name: Restart httpd Service
    service:
      name: httpd
      enabled: true
      state: started
  - name: open firewalld
    firewalld:
      service: http
      port: 80/tcp
